version: '3.1'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '172.18.0.1'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: demo_java
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - "./banco.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./test.sql:/docker-entrypoint-initdb.d/2.sql"